# Generated by Django 4.1.1 on 2022-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_user',
            old_name='tb_book',
            new_name='fk',
        ),
    ]
