# Generated by Django 4.1.1 on 2022-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_tb_book_tb_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
