# Generated by Django 4.1.1 on 2022-09-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_tb_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_book',
            name='text',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
